//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
[AddComponentMenu("UILogic/XUIMeditation")]
public class XUIMeditation : XDefaultFrame
{
	public XUIMeditation ()
	{

	}

	public UILabel cdtime;
	public UILabel rewardExp;

	public void SetTime(string timeValue)
	{
		cdtime.text = timeValue;
	}

	public void SetRewardExp(string exp)
	{
		rewardExp.text = exp;
	}
}